### ISSUE TITLE
Skipping extension with invalid URL

### ISSUE THREAD

**Issue by consunmida** [sentialx/electron-extensions#10]
when i used extension:
electron-extension://2.3.4.2_0                                                                       [15560:0924/141115.615:ERROR:CONSOLE(7946)] "Skipping extension with invalid URL: electron-extension ://2.3.4.2_0", source: devtools://devtools/bundled/shell.js (7946)

**Comment by sentialx** [comment]
That's because devtools extensions are not supported yet. However if you extension is not a devtools extension, you can ignore this error.
