### ISSUE TITLE
adding crx

### ISSUE THREAD

**Issue by lincolnaleixo** [sentialx/electron-extensions#13]
Is it possible to load extension from a .crx extension file, like that:

```
 const extensions = new ExtensibleSession(session.defaultSession);
 extensions.loadExtension('uBlock-Origin_v1.23.0.crx');
```

I tried with that code and didn't work

**Comment by sentialx** [comment]
The extension must be extracted

**Comment by lincolnaleixo** [comment]
I extracted and tried using full path or relative path of the folder. Didn't work. Thanks anyway
