### ISSUE TITLE
objectToArray function mangles requestHeaders and responseHeaders

### ISSUE THREAD

**Issue by slashedio** [sentialx/electron-extensions#15]
The following function in `web-request.ts` returns unexpected results:
```js
const objectToArray = (obj: any): any[] => {
  const arr: any = [];
  Object.keys(obj).forEach(k => {
    if (obj[k]) {
      arr.push({ name: k, value: obj[k][0] });
    }
  });
  return arr;
};
```

Rather than returning correct header value, it returns the first symbol of every header value.
Dropping the [0] fixes the problem.

**Comment by sentialx** [comment]
I believe it can be confusing...
