### ISSUE TITLE
Does it work with content scripts that do not run in background page?

### ISSUE THREAD

**Issue by kirilpopov** [sentialx/electron-extensions#17]
For example, if I have a config like this:

```json
{
  "manifest_version": 2,
  "name": "my extension",
  "version": "1.0",
  "content_scripts": [
    {
      "matches": [
        "https://*.google.com/*"
      ],
      "js": [
        "content.js"
      ]
    }
  ]
}
```

Will this inject my script when I open google.com and allow the script to work with the DOM?

Thank you

**Comment by sentialx** [comment]
It should work

**Comment by kirilpopov** [comment]
Hi, it seems my issue is related to adding a preload script - if I run the content script without having a preload script to **ExtensibleSession** it works fine.

However when I do this
```
const extensions = new ExtensibleSession(({
    preloadPath: resolve(__dirname, 'preload-script.js'),
}));
````

The content scripts is not executed any more (however the preload is).

I create a quick repro here - https://github.com/kirilpopov/electron-extension-issue-17

**Comment by sentialx** [comment]
@kirilpopov In your preload script you need to `require('electron-extensions/preload')`, or just specify the `preloadPath` to the path where the `electron-extensions/preload` script is.

**Comment by kirilpopov** [comment]
Thanks @sentialx , it works now. Closing the issue
