### ISSUE TITLE
Question: Can we load extensions from Web Stor?

### ISSUE THREAD

**Issue by hvaoc** [sentialx/electron-extensions#18]
I tried loading Grammarly from the file system, I don't get any errors but I don't see Grammarly active either. Usually, Chrome doesn't like extensions loaded from the filesystem.

Can you give me an example of how to load any of the Web Store extensions if that is possible?

**Comment by sentialx** [comment]
You need to extract the `crx` file. Also, you will need to implement `browserAction` by yourself.
