### ISSUE TITLE
windows.create in background page

### ISSUE THREAD

**Issue by vittoj** [sentialx/electron-extensions#23]
May it support windows.create in background page?

**Comment by sentialx** [comment]
It is already supported. #14

**Comment by vittoj** [comment]
> 
> 
> It is already supported. #14

Hi, I try to open the popup of an extension in background page,
```
chrome.windows.create({
	url: 'packages/popup/dist/index.html',
	type: 'popup',
	width: 360,
	height: 600,
	left: 80,
	top: 80
}, window => this.popup = window)
```
and this doesn't work, it does work in Chrome.
Any suggestions?
