### ISSUE TITLE
Active loaded extension

### ISSUE THREAD

**Issue by EliasSimoes** [sentialx/electron-extensions#25]
I have two extensions and i loaded them like this
![image](https://user-images.githubusercontent.com/19808684/84210686-b7dd4b80-aa8f-11ea-8764-1051c287778a.png)

The first question is: where my extension was loaded? 
If it was loaded at my main BrowserWindow object, how can i active it?

**Comment by sentialx** [comment]
You can access list of extensions under `extensions` array which is in your `ExtensibleSession` instance. What do you mean by 'how can i active it?'.

**Comment by EliasSimoes** [comment]
thank you for answer, i mean just like some chrome extensions that we click the icon button then it active the content.

**Comment by sentialx** [comment]
It is up to you to implement the UI related part. This package brings only the fundamental machinery like basic Chrome APIs to support extensions.

**Comment by EliasSimoes** [comment]
I'm going to implement it. Thank you one more time :)

**Comment by see7788** [comment]
``<img src="http://shuzijia.net/1.JPG"/>
``<img src="http://shuzijia.net/2.JPG"/>
``<img src="http://shuzijia.net/3.JPG"/>
Please help me

**Comment by see7788** [comment]
![4](https://user-images.githubusercontent.com/44776768/85235470-b7599300-b447-11ea-852d-315cd784e25b.JPG)

**Comment by sentialx** [comment]
@see7788 I think the path to the extension is invalid. Please double check.

**Comment by see7788** [comment]
I will zip the CRX. The path points to the directory, not to the file. Is that ok?

**Comment by sentialx** [comment]
Yes, it has to be an unpacked extension.

**Comment by see7788** [comment]
Thank you for the bag. Can you provide a complete example of the use of. CRX

extensions.loadExtension (`${__ Dirname} ${V} '); for V

**Comment by sentialx** [comment]
There is no CRX support.

**Comment by see7788** [comment]
![image](https://user-images.githubusercontent.com/44776768/85283624-41ddd900-b4c0-11ea-94fb-e9ebb59a704f.png)

**Comment by sentialx** [comment]
Wexond has its own extensions system with own crx extractor. It is not provided in this library.
