### ISSUE TITLE
chrome.tabs.getSelected() should not return an array on 7.0.0-beta.2

### ISSUE THREAD

**Issue by iwiedenm** [sentialx/electron-extensions#28]
I noticed this method is returning an array but the chrome docs specify that a `Tab` object should be returned: https://developer.chrome.com/extensions/tabs#method-getSelected

`./src/browser/tabs.ts`
```
public getSelected(windowId: number) {
  if (typeof windowId === 'number') {
    return this.query({ windowId, active: true });
  }
  return this.query({ active: true });
}
```
Should be...
```
public getSelected(windowId: number) {
  if (typeof windowId === 'number') {
    return this.query({ windowId, active: true })[0];
  }
  return this.query({ active: true })[0];
}
```

It's a very easy fix since the chrome.tabs.query() method will always return an array we just need to get the first element and return that.

Wanted to make a pull request but for some reason I can't find the code anymore for 7.0.0-beta.2, did it get taken down or something? It's not available on NPM...

**Comment by sentialx** [comment]
I messed up something yesterday, it should be back.
