### ISSUE TITLE
What does the License Mean?

### ISSUE THREAD

**Issue by rlingineni** [sentialx/electron-extensions#31]
@sentialx  Saw that there was patents file next to the Open Source License. Wasn't super sure what that meant?

Are we allowed to use this library to help in commercial Electron projects? Or does that mean we can pay/support this project and be granted a license. 

https://github.com/sentialx/electron-extensions/blob/master/PATENTS

What was your thinking here?

**Comment by sentialx** [comment]
It means that commercial use is not allowed
