### ISSUE TITLE
Not working with Electron 5?

### ISSUE THREAD

**Issue by IceHacks** [sentialx/electron-extensions#8]
### Problem:
I can't seem to get it working (content scripts work, but not my WebRequest background.js)

### Reproduction:
1. Create a new electron-forge app.
```bash
npx create-electron-app my-app
cd my-app
```
2. Install `electron-extensions`
```bash
npm i electron-extensions
```
3. Add code to `index.js`
```js
await extension.loadExtension(
	"/path/to/normal/extension/"
);
```
4. Start app
```bash
npm start
```

You should get this error:
```
 electron-extension://name
[12692:0727/103022.600:ERROR:CONSOLE(7817)] "Skipping extension with invalid URL: electron-extension://name", source: chrome-devtools://devtools/bundled/shell.js (7817)
```
but the content script should still load.

**Comment by sentialx** [comment]
Could you write steps to reproduce?

**Comment by IceHacks** [comment]
Yes sorry. I'll edit my post.

**Comment by sentialx** [comment]
Please, show me your full code of the extension loading part. Do you execute it in app `load` event?

**Comment by IceHacks** [comment]
@sentialx I put it in the "ready" event. Which is (from what I read) where it goes.

```js
...
const createWindow = async () => {
	var extension = new EE.ExtensibleSession(session.defaultSession);
	await extension.loadExtension(
		"path"
	);
	// Create the browser window.
	mainWindow = new BrowserWindow({
		width: 800,
		height: 600
	});

	mainWindow.loadURL("path");

	mainWindow.webContents.openDevTools();

	mainWindow.on("closed", () => {
		mainWindow = null;
	});
};
app.on("ready", createWindow);
...
```

**Comment by sentialx** [comment]
What isn't working in `webRequest`?

**Comment by IceHacks** [comment]
The background.js should block the loading of a file and replace it (using `chrome.tabs.executeScript`).

here is a sample:
```
chrome.webRequest.onBeforeRequest.addListener(
	function (details) {
		if (details.url.includes("something")) {
			inject();
			return { cancel: true };
		}
	},
	{
		urls: chrome.runtime.getManifest()["externally_connectable"].matches
	},
	["blocking"]
);
```

all the APIs should be supported

**Comment by IceHacks** [comment]
Wait a second. The thing that isn't working is not the blocking but another feature I am using. One sec. (I'll edit this)

**Comment by IceHacks** [comment]
Any discoveries?

**Comment by sentialx** [comment]
@IceHacks Not yet. I will need to test it out.

**Comment by IceHacks** [comment]
ok @sentialx if you need any more resources from me I should be able to get them.

**Comment by sentialx** [comment]
@IceHacks Could you create a repo to reproduce this (with manifest.json and all needed things to get it to run)?

**Comment by IceHacks** [comment]
I'll see what I can do @sentialx

**Comment by IceHacks** [comment]
@sentialx https://github.com/IceHacks/example-of-brokeness Just do `npm i && npm start`, the extension should not work. Then load the extension in chrome, it should work.

**Comment by IceHacks** [comment]
Don't know if you saw this :smile: just for good measure. I know you are busy.

**Comment by sentialx** [comment]
I saw, thanks

**Comment by sentialx** [comment]
@IceHacks Is it fixed?

**Comment by IceHacks** [comment]
No, but I found my own solution. It was probably just me doing something wrong.
